######################################################################
# Automatically generated by qmake (3.0) Fri Apr 25 19:35:22 2014
######################################################################

TEMPLATE = app
TARGET = OpenOCD-QtGUI
INCLUDEPATH += . QtTelnet

QT += network widgets
HEADERS += mainwidget.h QtTelnet/qttelnet.h
FORMS += mainwidget.ui
SOURCES += main.cpp mainwidget.cpp QtTelnet/qttelnet.cpp
